services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/fashion_db
      - SECRET_KEY=your-secret-key-here
      - INTERNAL_TOKEN=YOU-API-KEY
    depends_on:
      - db
      - agent
    command: uvicorn app.main:app --host 0.0.0.0 --reload

  agent:
    build: 
      context: .
      dockerfile: Dockerfile.agent
    ports:
      - "8001:8001"
    environment:
      - HF_TOKEN=YOU-API-KEY
      - INTERNAL_TOKEN=YOU-API-KEY
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fashion_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: 